security:
    encoders:
        Angle\NickelTracker\CoreBundle\Entity\AdminUser:
            algorithm:          sha1
            encode_as_base64:   false
            iterations:         1

        Angle\NickelTracker\CoreBundle\Entity\User:
            algorithm:          sha1
            encode_as_base64:   false
            iterations:         1

    providers:
            main:
                entity:
                    class:  Angle\NickelTracker\CoreBundle\Entity\AdminUser
                    property: username

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        ROLE_SYSTEM_ADMIN:  ROLE_SUPER_ADMIN


    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        login_firewall:
            pattern:    ^/login$
            security:   false
        secured_area:
            pattern:    ^/
            form_login:
                login_path:  /login
                check_path:  /login/check
                default_target_path: /
            logout:
                path:   /logout
                target: /login

    access_control:
        # ROLE_SYSTEM_ADMIN
        # ROLE_SUPER_ADMIN
        # ROLE_ADMIN
        # ROLE_USER
        - { path: ^/, roles: ROLE_USER }

