## SECURITY
angle_nt_app_login:
    pattern:    /login
    defaults:   { _controller: AngleNickelTrackerAppBundle:Security:login }

angle_nt_app_login_check:
    pattern:    /login/check

angle_nt_app_logout:
    pattern:    /logout

## Dashboard
angle_nt_app_dashboard:
    pattern:    /
    defaults:   { _controller: AngleNickelTrackerAppBundle:Dashboard:home }


## Account
angle_nt_app_account_list:
    pattern:    /account
    defaults:   { _controller: AngleNickelTrackerAppBundle:Account:list }

angle_nt_app_account_update_name:
    pattern:    /account/updateName
    defaults:   { _controller: AngleNickelTrackerAppBundle:Account:changeName }
    methods:    [POST]
    requirements:
        _format: json

angle_nt_app_account_process:
    pattern:    /account/process/{id}
    defaults:   { _controller: AngleNickelTrackerAppBundle:Account:process, id: null }
    requirements:
        id:     \d+

angle_nt_app_account_delete:
    pattern:    /account/delete
    defaults:   { _controller: AngleNickelTrackerAppBundle:Account:delete }
    methods:    [POST]


## Category
angle_nt_app_category_list:
    pattern:    /category
    defaults:   { _controller: AngleNickelTrackerAppBundle:Category:list}

angle_nt_app_category_process:
    pattern:    /category/process/{id}
    defaults:   { _controller: AngleNickelTrackerAppBundle:Category:process }
    requirements:
        id:     \d+
angle_nt_app_category_view:
    pattern:    /category/view/{id}
    defaults:   { _controller: AngleNickelTrackerAppBundle:Category:view }
    requirements:
        id:     \d+

angle_nt_app_category_delete:
    pattern:    /category/delete
    defaults:   { _controller: AngleNickelTrackerAppBundle:Category:delete }
    methods:    [POST]


## Transaction
# This one also includes filters
angle_nt_app_transaction_list:
    pattern:    /transaction
    defaults:   { _controller: AngleNickelTrackerAppBundle:Transaction:list }

angle_nt_app_transaction_view:
    pattern:    /transaction/view/{id}
    defaults:   { _controller: AngleNickelTrackerAppBundle:Transaction:view }
    requirements:
        id:     \d+

angle_nt_app_transaction_delete:
    pattern:    /transaction/delete
    defaults:   { _controller: AngleNickelTrackerAppBundle:Transaction:delete }
    methods:    [POST]

angle_nt_app_transaction_new_income:
    pattern:    /transaction/new/income
    defaults:   { _controller: AngleNickelTrackerAppBundle:Transaction:newIncomeProcess }

angle_nt_app_transaction_new_expense:
    pattern:    /transaction/new/expense
    defaults:   { _controller: AngleNickelTrackerAppBundle:Transaction:newExpenseProcess }

angle_nt_app_transaction_new_transfer:
    pattern:    /transaction/new/transfer
    defaults:   { _controller: AngleNickelTrackerAppBundle:Transaction:newTransferProcess }

## Report
angle_nt_app_report_list:
    pattern:    /report
    defaults:   { _controller: AngleNickelTrackerAppBundle:Report:list }

angle_nt_app_report_monthly_balance:
    pattern:    /report/monthly-balance
    defaults:   { _controller: AngleNickelTrackerAppBundle:Report:monthlyBalance }